import React from 'react';
import Head from 'next/head'
import HomeContainer from '../containers/HomeContainer';

export default function Home(initData) {

  return (
    <div className="container">
      <Head>
        <title>Create Giphy App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="/style.css" />
        <meta name="description" content="This is a Giphy search app. Find giphy quickly" />
      </Head>
      <HomeContainer data={initData.catGiphys.data} />
    </div>
  )
}

export async function getStaticProps () {
  let catGiphys = await fetch('https://api.giphy.com/v1/gifs/search?q=cats&api_key=nFR45YvPhD3AR8iV1IPOZle5m0c1sApv&limit=20')
  catGiphys = await catGiphys.json()  
  return {props: {catGiphys}}
}